<script lang="ts">
  import { onMount, tick } from 'svelte';
  import SensorPanel from './components/SensorPanel.svelte';
  import About from './components/About.svelte';
  import SnapshotActions from './components/SnapshotActions.svelte';
  let showHidden = $state(false);
  import { Wifi, LayoutDashboard, ShieldCheck, Radio, History, ListChecks, Download, Upload, Search, ChevronRight, ArrowUpRight, CircleHelp, LockKeyhole, Activity, Check, AlertTriangle, X, RefreshCw, HardDrive, Bluetooth, Nfc } from '@lucide/svelte';
  import type { AP, Scan, Finding, Difference } from './types';
  let scans = $state<Scan[]>([]), scan = $state<Scan | null>(null), selected = $state<AP | null>(null);
  let page = $state('Overview'), query = $state(''), band = $state('all'), severity = $state('all');
  let busy = $state(false), error = $state(''), notice = $state(''), inventoryText = $state(''), from = $state(''), to = $state(''), difference = $state<Difference | null>(null);
  let upload = $state<HTMLInputElement>(null!);
  const navigation = [{ name: 'Overview', icon: LayoutDashboard }, { name: 'Findings', icon: ShieldCheck }, { name: 'RF environment', icon: Radio }, { name: 'History', icon: History }, { name: 'Authorized networks', icon: ListChecks }, { name: 'Bluetooth', icon: Bluetooth }, { name: 'NFC', icon: Nfc }, { name: 'About', icon: CircleHelp }];
  const date = (value: string) => new Date(value).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
  let owned = $derived(scan?.access_points.filter(a => a.authorized) ?? []);
  let networks = $derived(new Set(owned.map(a => a.ssid)).size);
  let filtered = $derived((scan?.access_points ?? []).filter(a => (band === 'all' || a.band === band) && `${a.ssid} ${a.bssid}`.toLowerCase().includes(query.toLowerCase())));
  let findings = $derived((scan?.findings ?? []).filter(f => (severity === 'all' || f.severity === severity) && `${f.title} ${f.ssid} ${f.bssid}`.toLowerCase().includes(query.toLowerCase())));
  let selectedFindings = $derived(scan?.findings.filter(f => f.bssid === selected?.bssid) ?? []);
  let channels = $derived([...new Set(filtered.map(a => a.channel))].filter(Boolean).sort((a,b) => a-b));
  async function api(path: string, options?: RequestInit) {
    const response = await fetch('/api' + path, { ...options, headers: { 'X-Wifi-Scanner': 'local', ...options?.headers } });
    if (!response.ok) { const text = await response.text(); try { throw new Error(JSON.parse(text).error); } catch(e) { if (e instanceof SyntaxError) throw new Error(text); throw e; } }
    return response.json();
  }
  async function refresh(id?: string) {
    scans = await api(`/scans?include_hidden=${showHidden}`); scan = scans.find(s => s.id === (id ?? scan?.id)) ?? scans.find(s => !s.hidden) ?? scans[0] ?? null;
    selected = scan?.access_points.find(a => a.bssid === selected?.bssid) ?? scan?.access_points[0] ?? null;
    inventoryText = JSON.stringify(await api('/inventory'), null, 2);
    from = scans[1]?.id ?? ''; to = scans[0]?.id ?? ''; difference = null;
  }
  async function work(fn: () => Promise<void>) { busy = true; error = ''; notice = ''; try { await fn(); } catch(e) { error = e instanceof Error ? e.message : String(e); } finally { busy = false; } }
  onMount(() => {
    const section = window.location.hash.slice(1);
    if (['about', 'measurements', 'scan-process', 'glossary', 'data-limits'].includes(section)) {
      page = 'About';
      tick().then(() => document.getElementById(section)?.scrollIntoView());
    }
    work(() => refresh());
  });
  function navigate(name: string) { page = name; query = ''; band = 'all'; severity = 'all'; window.history.replaceState(null, '', name === 'About' ? '#about' : '#overview'); window.scrollTo({ top: 0 }); }
  async function importCapture(event: Event) {
    const input = event.target as HTMLInputElement, file = input.files?.[0]; if (!file) return;
    await work(async () => { if (file.size > 32*1024*1024) throw new Error('Capture must be 32 MB or smaller.'); const s = await api('/import', { method: 'POST', body: file }); await refresh(s.id); navigate('Overview'); notice = `Imported ${file.name}. ${s.access_points.length} access points observed.`; }); input.value = '';
  }
  async function saveInventory() { await work(async () => { const value = JSON.parse(inventoryText); await api('/inventory', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(value) }); notice = 'Authorization inventory saved. Reassess the latest capture to apply it; historical scans retain their original findings.'; }); }
  async function reassess() { await work(async () => { const s = await api('/reassess', { method: 'POST' }); await refresh(s.id); notice = 'Created a new assessment using the current inventory.'; }); }
  async function compare() { await work(async () => { difference = await api(`/diff?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`); }); }
  async function manageSnapshot(s: Scan, action: 'hide' | 'restore' | 'delete') {
    await work(async () => {
      await api(`/scans/${s.id}`, action === 'delete' ? { method: 'DELETE' } : { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ hidden: action === 'hide' }) });
      await refresh();
      notice = action === 'delete' ? 'Snapshot deleted.' : action === 'hide' ? 'Snapshot hidden. Enable Show hidden snapshots to restore it.' : 'Snapshot restored.';
    });
  }
  function chooseScan(id: string) { scan = scans.find(s => s.id === id) ?? null; selected = scan?.access_points[0] ?? null; }
  function status(a: AP) { if (!a.authorized) return scan?.findings.some(f => f.bssid === a.bssid) ? 'Review AP' : 'Neighbor'; const n = scan?.findings.filter(f => f.bssid === a.bssid).length ?? 0; return n ? `${n} finding${n > 1 ? 's' : ''}` : 'No findings'; }
  function spectrum(a: AP, i: number) { const x = 48 + i * (600 / Math.max(filtered.length,1)); const h = Math.max(12, Math.min(130, ((a.rssi ?? -90)+95)*2)); return `M ${x-24} 165 Q ${x-12} ${165-h}, ${x+18} ${165-h} Q ${x+48} ${165-h}, ${x+60} 165 Z`; }
</script>

<svelte:head><title>{page} · Signal Atlas</title></svelte:head>
<div class="app-shell">
  <aside class="sidebar">
    <a class="brand" href="#overview" onclick={() => navigate('Overview')}><span class="brand-mark"><Wifi size={25}/></span><span>Signal Atlas<small>LOCAL DISCOVERY</small></span></a>
    <div class="workspace"><span class="workspace-icon"><HardDrive size={17}/></span><div>Local workspace<small>On this device</small></div><LockKeyhole size={14}/></div>
    <p class="nav-label">WORKSPACE</p>
    <nav aria-label="Main navigation">{#each navigation as item}<button aria-label={item.name} aria-current={page === item.name ? 'page' : undefined} class:active={page === item.name} onclick={() => navigate(item.name)}><item.icon size={19}/><span>{item.name}</span>{#if item.name === 'Findings' && scan?.findings.length}<span class="nav-count">{scan.findings.length}</span>{/if}</button>{/each}</nav>
    <div class="local-note"><ShieldCheck size={21}/><strong>Your network. Your data.</strong><p>Captures and findings stay on this device.</p><span>Local storage · No cloud sync</span></div>
    <div class="sidebar-footer"><span class="version">v0.2.0</span><span>Independent services</span></div>
  </aside>
  <div class="main-shell">
    <header class="topbar"><div class="breadcrumb">Workspace <ChevronRight size={14}/> <strong>{page}</strong></div><span class="local-badge"><LockKeyhole size={13}/> Local only</span></header>
    <main>
      {#if page === 'About'}
        <About/>
      {:else if page === 'Bluetooth' || page === 'NFC'}
        {#key page}<SensorPanel protocol={page === 'Bluetooth' ? 'bluetooth' : 'nfc'}/>{/key}
      {:else}
      <div class="page-heading"><div><p class="eyebrow">WIRELESS OBSERVABILITY</p><h1>{page === 'Overview' ? 'Your wireless security, in view.' : page}</h1><p class="subtitle">{page === 'Overview' ? 'Understand your access points. Investigate what needs attention.' : page === 'Findings' ? 'Observed risks, supporting evidence, and a clear next step.' : page === 'RF environment' ? 'Signal strength and channel observations from the selected capture.' : page === 'History' ? 'Compare snapshots and see what changed.' : 'Define exactly which networks and access points you manage.'}</p></div><div class="heading-actions">{#if scan}<details class="export-menu"><summary><Download size={16}/> Export</summary><div>{#each ['json','sarif','html'] as format}<a href={`/api/export/${scan.id}?format=${format}`}>{format.toUpperCase()} report</a>{/each}</div></details>{/if}<button class="primary" disabled={busy} onclick={() => upload.click()}><Upload size={16}/>{busy ? 'Working…' : 'Import capture'}</button><input bind:this={upload} type="file" accept=".pcap,.pcapng,.cap" onchange={importCapture} hidden/></div></div>
      {#if error}<div class="message error" role="alert"><AlertTriangle size={18}/><span>{error}</span><button aria-label="Dismiss error" onclick={() => error = ''}><X size={16}/></button></div>{/if}
      {#if notice}<div class="message success" role="status"><Check size={18}/><span>{notice}</span><button aria-label="Dismiss notification" onclick={() => notice = ''}><X size={16}/></button></div>{/if}
      <div class="snapshot-toolbar"><label><input type="checkbox" bind:checked={showHidden} disabled={busy} onchange={() => work(() => refresh())}/> Show hidden snapshots</label>{#if scan}{#key scan.id}<SnapshotActions id={scan.id} label={`${date(scan.created_at)} · ${scan.source}`} hidden={scan.hidden} disabled={busy} onaction={action => manageSnapshot(scan!, action)}/>{/key}{/if}</div>
      {#if scan}<div class="scan-bar"><span class:demo={scan.source.includes('demo')} class="source-label">{scan.source.includes('demo') ? 'DEMO DATA' : 'SAVED OBSERVATION'}</span><span>{date(scan.created_at)}</span><span class="scan-source">{scan.source}</span><label class="scan-picker">Snapshot <select value={scan.id} onchange={e => chooseScan(e.currentTarget.value)}>{#each scans as s}<option value={s.id}>{date(s.created_at)} · {s.id.slice(-6)}{s.hidden ? ' · Hidden' : ''}</option>{/each}</select></label></div>{/if}
      {#if page === 'Authorized networks'}
        <div class="inventory-grid"><section class="panel editor"><div class="panel-heading"><h2>Authorization inventory</h2><span class="badge neutral">Exact BSSIDs only</span></div><p>SSID names alone do not establish ownership. Add the exact BSSIDs from your router or controller.</p><label for="inventory">Network configuration · JSON</label><textarea id="inventory" bind:value={inventoryText} spellcheck="false" rows="20"></textarea><div class="editor-actions"><button class="primary" disabled={busy} onclick={saveInventory}>Save inventory</button><button class="secondary" disabled={busy || !scans.some(s => !s.hidden)} onclick={reassess}><RefreshCw size={15}/> Reassess latest capture</button></div></section><section class="panel scope-card"><ShieldCheck size={30}/><h2>Authorization is explicit</h2><p>Passive captures can include neighboring APs. Security scoring covers allowlisted APs; unknown BSSIDs using an owned SSID are flagged for review.</p><h3>Active checks</h3><p>Run from the CLI on Linux. They require an exact connected SSID/BSSID match, an explicit target list, and confirmation for that run.</p><code>wifi-scan audit --network Home --active --confirm-active --interface wlan0</code><p>At most eight TCP address/port pairs, once per network every five minutes. A reachable service is an observation, not proof of a vulnerability.</p><h3>Configuration example</h3><pre>{`{"authorized": [{
  "ssid": "Home",
  "bssids": ["02:11:22:33:44:55"],
  "targets": [{
    "ip": "192.168.1.1",
    "ports": [443]
  }]
}]}`}</pre></section></div>
      {:else if !scan}
        <section class="panel empty-state"><div class="empty-icon"><Radio size={40}/></div><h2>No visible snapshots</h2><p>Import a PCAP or PCAPNG containing 802.11 beacon or probe-response frames. Your access points, findings, and RF observations will appear here. Enable Show hidden snapshots to find captures you previously hid.</p><button class="primary" disabled={busy} onclick={() => upload.click()}><Upload size={16}/> Import your first capture</button><div class="empty-options"><div><strong>Live passive discovery · Linux</strong><code>wifi-scan discover --interface mon0</code></div><div><strong>Explore the sample workspace</strong><code>make demo</code></div></div></section>
      {:else if page === 'Overview'}
        <div class="metrics"><section class="panel score-card"><div class="score-ring" style={`--score:${scan.score ?? 0}`}><div><strong>{scan.score ?? '—'}</strong><span>/ 100</span></div></div><div><p class="metric-label">Configuration score <CircleHelp size={14}/></p><strong class="score-caption">{scan.score === null ? (owned.length ? 'Incomplete capture' : 'Awaiting scope') : scan.score >= 90 ? 'Strong baseline' : scan.score >= 70 ? 'Room to improve' : 'Needs attention'}</strong><small>{owned.length} authorized APs assessed</small></div></section><section class="panel metric"><span class="metric-label">Owned networks <Wifi size={18}/></span><strong>{networks}<small>SSIDs</small></strong><span class="metric-foot">{owned.length} authorized access points</span></section><section class="panel metric"><span class="metric-label">Observed access points <Radio size={18}/></span><strong>{scan.access_points.length}<small>APs</small></strong><span class="metric-foot">Across {new Set(scan.access_points.map(a => a.band)).size} frequency bands</span></section><section class="panel metric"><span class="metric-label">Security findings <ShieldCheck size={18}/></span><strong>{scan.findings.length}<small>to review</small></strong><div class="severity-counts"><span class="critical">{scan.findings.filter(f => f.severity === 'critical').length} critical</span><span class="high">{scan.findings.filter(f => f.severity === 'high').length} high</span></div></section></div>
        <div class="overview-grid"><section class="panel ap-panel"><div class="panel-heading"><div><h2>Access points <span class="count">{scan.access_points.length}</span></h2><p>Your infrastructure and the surrounding airspace.</p></div><Radio size={18}/></div><div class="table-controls"><div class="search"><Search size={16}/><input aria-label="Search access points" placeholder="Search SSID or BSSID…" bind:value={query}/></div><div class="segmented" aria-label="Frequency band">{#each ['all','2.4','5','6'] as b}<button class:chosen={band === b} onclick={() => band = b}>{b === 'all' ? 'All bands' : `${b} GHz`}</button>{/each}</div></div><div class="table-wrap"><table><thead><tr><th>NETWORK / BSSID</th><th>SIGNAL</th><th>SECURITY</th><th>STATUS</th></tr></thead><tbody>{#each filtered as a}<tr class:selected={selected?.bssid === a.bssid}><td><button class="ap-select" onclick={() => selected = a}><span class="ap-icon" class:owned={a.authorized}><Wifi size={17}/></span><span><strong>{a.ssid || 'Hidden SSID'}</strong><small>{a.bssid}</small></span></button></td><td><span class="signal-cell"><span class="signal-bars" aria-hidden="true">{#each [1,2,3,4] as n}<i class:lit={(a.rssi ?? -100) > -100+n*12} style={`height:${4+n*3}px`}></i>{/each}</span>{a.rssi ?? '—'}<small>dBm</small></span><small class="muted">{a.band} GHz · Ch {a.channel || '—'}</small></td><td><span class="protocol">{a.security.protocol}</span><small class="muted">PMF {a.security.pmf}</small></td><td><span class="badge" class:good={status(a) === 'No findings'} class:warning={status(a).includes('finding') && status(a) !== 'No findings' || status(a) === 'Review AP'} class:neutral={status(a) === 'Neighbor'}>{status(a)}</span></td></tr>{:else}<tr><td colspan="4" class="no-results">No access points match your filters.</td></tr>{/each}</tbody></table></div><div class="table-footer"><span>{filtered.length} of {scan.access_points.length} access points</span><span>Beacon & probe-response observations</span></div></section>
        <aside class="panel detail-panel">{#if selected}<div class="panel-heading"><span class="detail-label">ACCESS POINT DETAILS</span><span class="ap-icon owned"><Wifi size={18}/></span></div><h2>{selected.ssid || 'Hidden SSID'}</h2><code class="detail-bssid">{selected.bssid}</code><span class="badge" class:good={selected.authorized} class:neutral={!selected.authorized}>{selected.authorized ? 'Authorized access point' : 'Outside authorized inventory'}</span><dl><div><dt>Security</dt><dd>{selected.security.protocol}</dd></div><div><dt>Authentication</dt><dd>{selected.security.akm.join(', ') || 'None observed'}</dd></div><div><dt>Cipher</dt><dd>{selected.security.ciphers.join(', ') || 'None observed'}</dd></div><div><dt>PMF</dt><dd>{selected.security.pmf}</dd></div><div><dt>Radio</dt><dd>{selected.band} GHz · Ch {selected.channel || '—'}</dd></div><div><dt>Channel width</dt><dd>{selected.width ? `${selected.width} MHz` : 'Unknown'}</dd></div><div><dt>Generation</dt><dd>{selected.generation === 'Unknown' ? 'Unknown' : `Wi-Fi ${selected.generation}`}</dd></div><div><dt>First observed</dt><dd>{date(selected.first_seen)}</dd></div><div><dt>Last observed</dt><dd>{date(selected.last_seen)}</dd></div></dl><div class="detail-assessment"><strong>{selectedFindings.length ? `${selectedFindings.length} finding${selectedFindings.length === 1 ? '' : 's'} to review` : selected.authorized ? 'No configuration findings' : 'Not assessed'}</strong><p>{selectedFindings[0]?.title ?? (selected.authorized ? 'No issues identified by the current rules in this capture.' : 'Add this BSSID to your inventory only if you manage it.')}</p>{#if selectedFindings.length}<button onclick={() => { page = 'Findings'; query = selected!.bssid; }}>View evidence <ArrowUpRight size={16}/></button>{/if}</div>{/if}</aside></div>
        <div class="bottom-grid"><section class="panel attention"><div class="panel-heading"><h2>Worth a closer look</h2><button class="text-button" onclick={() => navigate('Findings')}>All findings <ArrowUpRight size={15}/></button></div>{#each scan.findings.slice(0,2) as f}<button class="finding-preview" onclick={() => { page = 'Findings'; query = f.bssid; }}><span class="alert-icon"><AlertTriangle size={18}/></span><span><strong>{f.title}</strong><small>{f.ssid} · {f.bssid}</small></span><span class="badge warning">{f.severity}</span><ChevronRight size={16}/></button>{:else}<p class="quiet">No findings in the assessed scope.</p>{/each}</section><section class="panel capture-note"><Activity size={22}/><div><h2>A snapshot, not a guarantee</h2><p>Scores summarize observed configuration on authorized APs. Password strength, client behavior, and controller settings are not inferred from beacons.</p><button class="text-button" onclick={() => navigate('History')}>Explore scan history <ArrowUpRight size={15}/></button></div></section></div>
      {:else if page === 'Findings'}
        <div class="findings-toolbar"><div class="search"><Search size={16}/><input aria-label="Search findings" placeholder="Search findings, SSID, or BSSID…" bind:value={query}/></div><div class="segmented">{#each ['all','critical','high','medium','low'] as s}<button class:chosen={severity === s} onclick={() => severity = s}>{s === 'all' ? 'All severities' : s}</button>{/each}</div><span class="muted">{findings.length} findings</span></div><div class="findings-list">{#each findings as f}<article class="panel finding-card"><div class="finding-top"><span class="badge" class:danger={f.severity === 'critical'} class:warning={f.severity !== 'critical'}>{f.severity}</span><code>{f.rule_id}</code><span class="confidence">{f.confidence}% confidence</span></div><h2>{f.title}</h2><p class="finding-network">{f.ssid} <span>·</span> <code>{f.bssid}</code></p><div class="finding-columns"><div><h3>Observed evidence</h3><ul>{#each f.evidence as e}<li>{e}</li>{/each}</ul><h3>Why it matters</h3><p>{f.why_it_matters}</p></div><div class="remediation"><ShieldCheck size={21}/><h3>Recommended action</h3><p>{f.remediation}</p></div></div></article>{:else}<section class="panel empty-state"><ShieldCheck size={35}/><h2>No matching findings</h2><p>Try another filter, or review your authorized network inventory.</p></section>{/each}</div>
      {:else if page === 'RF environment'}
        <div class="rf-header"><div class="segmented">{#each ['all','2.4','5','6'] as b}<button class:chosen={band === b} onclick={() => band = b}>{b === 'all' ? 'All bands' : `${b} GHz`}</button>{/each}</div><span class="muted">{filtered.length} observed APs · Signal is received power, not throughput</span></div><section class="panel spectrum"><div class="panel-heading"><div><h2>Signal observations</h2><p>One curve per access point, ordered by network name. Height represents received signal.</p></div><Radio size={21}/></div><svg viewBox="0 0 740 215" role="img" aria-label="Access point signal strengths"><line x1="20" y1="165" x2="720" y2="165" stroke="#d4dfe4"/>{#each filtered as a,i}<path d={spectrum(a,i)} fill={['#14998930','#427bd330','#eeb54430'][i%3]} stroke={['#149989','#427bd3','#c89526'][i%3]} stroke-width="2"/><text x={48+i*(600/Math.max(filtered.length,1))+18} y="192" text-anchor="middle" fill="#5d6b7a" font-size="11">{a.rssi ?? '?'} dBm</text>{/each}</svg><div class="rf-legend">{#each filtered as a,i}<span><i style={`background:${['#149989','#427bd3','#c89526'][i%3]}`}></i>{a.ssid || 'Hidden'} · {a.band} GHz / {a.channel}</span>{/each}</div></section><section class="panel channel-panel"><div class="panel-heading"><h2>Primary channel occupancy</h2><span class="muted">AP counts · Not airtime utilization</span></div><div class="channel-grid">{#each channels as ch}<div class="channel"><span>Channel {ch}</span><strong>{filtered.filter(a => a.channel === ch).length}<small>APs</small></strong><div class="channel-meter"><i style={`width:${Math.min(100,filtered.filter(a => a.channel === ch).length*25)}%`}></i></div><small>{filtered.filter(a => a.channel === ch).map(a => `${a.band} GHz / ${a.width ?? '?'} MHz`).join(' · ')}</small></div>{/each}</div><p class="rf-caveat">Channel width, signal strength, and overlapping frequencies affect interference. These observations do not measure channel utilization or identify a universally “best” channel.</p></section>
      {:else if page === 'History'}
        <section class="panel compare-panel"><div class="panel-heading"><h2>Compare two snapshots</h2><History size={19}/></div>{#if scans.length > 1}<div class="compare-controls"><label>Earlier snapshot<select bind:value={from}>{#each scans as s}<option value={s.id}>{date(s.created_at)} · {s.id.slice(-6)}{s.hidden ? ' · Hidden' : ''}</option>{/each}</select></label><ChevronRight size={20}/><label>Later snapshot<select bind:value={to}>{#each scans as s}<option value={s.id}>{date(s.created_at)} · {s.id.slice(-6)}{s.hidden ? ' · Hidden' : ''}</option>{/each}</select></label><button class="primary" disabled={busy || from === to} onclick={compare}>Compare scans</button></div>{:else}<p>Import another capture or reassess after updating your inventory to compare observations.</p>{/if}{#if difference}<div class="diff-results"><h3>{difference.changes.length} observed changes</h3>{#each difference.changes as c}<div class="change-row"><span class="badge neutral">{c.kind}</span><div><strong>{c.ssid || 'Hidden SSID'}</strong><p>{c.detail}</p><code>{c.bssid}</code></div></div>{:else}<p>No configuration, inventory observation, or finding changes between these snapshots.</p>{/each}</div>{/if}</section><section class="panel history-panel"><div class="panel-heading"><h2>Saved snapshots</h2><span class="muted">Latest 100</span></div>{#each scans as s (s.id)}<div class="managed-history-row"><button class="history-row" onclick={() => { chooseScan(s.id); navigate('Overview'); }}><span class="history-icon"><History size={18}/></span><span><strong>{date(s.created_at)}</strong><small>{s.source} · {s.id}</small></span><span>{s.access_points.length} APs</span><span>{s.findings.length} findings</span><strong class="history-score">{s.score ?? '—'}<small>/ 100</small></strong><ChevronRight size={17}/></button><SnapshotActions id={s.id} label={`${date(s.created_at)} · ${s.source}`} hidden={s.hidden} disabled={busy} onaction={action => manageSnapshot(s, action)}/></div>{/each}</section>
      {/if}
      {#if scan?.warnings.length}<details class="capture-warnings"><summary><CircleHelp size={15}/> Capture notes ({scan.warnings.length})</summary><ul>{#each scan.warnings as w}<li>{w}</li>{/each}</ul></details>{/if}
      <footer class="main-footer"><span><LockKeyhole size={13}/> Stored locally in SQLite</span><span>{scan ? `Rules ${scan.rule_version} · ${scan.id}` : 'Ready for your first observation'}</span></footer>
      {/if}
    </main>
  </div>
</div>
