#!/usr/bin/env python3
"""Collect notices from resolved dependencies; run after npm ci and native setup."""
import argparse
import json
import os
from pathlib import Path
import re
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]


def output(*args, **kwargs):
    return subprocess.check_output(args, text=True, cwd=ROOT, **kwargs)


def notices(source, destination):
    found = []
    for item in sorted(Path(source).iterdir()):
        if item.is_file() and item.suffix.lower() in ('', '.txt', '.md', '.rst') and item.name.lower().startswith(('license', 'copying', 'notice', 'authors', 'patents')):
            destination.mkdir(parents=True, exist_ok=True)
            target = destination / item.name
            shutil.copyfile(item, target)
            found.append(f'[{item.name}]({target.relative_to(ROOT).as_posix()})')
    return ', '.join(found)


def slug(name):
    return re.sub(r'[^a-zA-Z0-9._-]', '_', name)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--python', default=str(ROOT / '.venv/bin/python'), help='interpreter containing optional native providers')
    args = parser.parse_args()
    text = ['# Third-party notices\n',
            'Generated by `scripts/collect_notices.py` from resolved dependency files.\n',
            'Signal Atlas original code is MIT licensed. Upstream components retain their own licenses. '
            'Keep this file and `licenses/` with redistributed builds. These copies are notices, not vendored dependency source.\n',
            '## Go executable dependencies\n',
            'The following modules are in the command dependency graphs for Linux, macOS, or Windows. '
            'Platform-specific packages may differ in a particular binary.\n',
            '| Module | Version | Upstream notices |\n| --- | --- | --- |']
    modules = set()
    for target in ('linux', 'darwin', 'windows'):
        env = dict(os.environ, GOOS=target, GOARCH='amd64', CGO_ENABLED='0')
        data = output('go', 'list', '-deps', '-f', '{{if .Module}}{{.Module.Path}}|{{.Module.Version}}|{{.Module.Dir}}{{end}}', './src/cmd/...', env=env)
        modules.update(tuple(line.split('|', 2)) for line in data.splitlines() if line)
    for name, version, directory in sorted(modules):
        if Path(directory).resolve() == ROOT:
            continue
        links = notices(directory, ROOT / 'licenses/go' / slug(name))
        if not links:
            raise RuntimeError(f'No upstream notice found for {name}')
        text.append(f'| `{name}` | `{version}` | {links} |')
    goroot = Path(output('go', 'env', 'GOROOT').strip())
    links = notices(goroot, ROOT / 'licenses/go-toolchain')
    if not (goroot / 'LICENSE').is_file():
        # Some packaged Go installations omit the top-level license file.
        extra = notices(ROOT / 'licenses/upstream/go', ROOT / 'licenses/go-toolchain')
        links = ', '.join(filter(None, (links, extra)))
    text += ['', f'Go runtime/standard library: {output("go", "env", "GOVERSION").strip()}. {links}.\n',
             '## Frontend and development dependencies\n',
             'Versions and license identifiers below come from `package-lock.json`. Full upstream notices '
             'are copied for locally installed packages. Optional platform binaries absent from this install '
             'are recorded in the lockfile and retain the notices supplied by their own packages. '
             'Build tools are installed separately, not shipped as application source.\n',
             '| Package | Version | Package license field | Upstream notices |\n| --- | --- | --- | --- |']
    lock = json.loads((ROOT / 'package-lock.json').read_text())
    for location, package in sorted(lock['packages'].items()):
        if not location:
            continue
        name = location.removeprefix('node_modules/')
        directory = ROOT / location
        links = notices(directory, ROOT / 'licenses/npm' / slug(name)) if directory.exists() else 'Optional platform package; see its distributed notice'
        if not links and directory.exists():
            if name.startswith('@rolldown/binding-'):
                links = notices(ROOT / 'node_modules/rolldown', ROOT / 'licenses/npm' / slug(name))
            elif name in ('is-reference', 'locate-character'):
                target = ROOT / 'licenses/npm' / slug(name) / 'README.md'
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(directory / 'README.md', target)
                links = f'[Upstream README/license declaration]({target.relative_to(ROOT).as_posix()}); author: Rich Harris (no separate license file shipped)'
        text.append(f'| `{name}` | `{package["version"]}` | `{package.get("license", "See upstream")}` | {links or "See package upstream"} |')
    text += ['', 'Lucide’s copied license includes both its ISC notice and the MIT notice for Feather-derived icons.\n',
             '## Optional native provider dependencies\n',
             'These packages are installed into a user-created virtual environment. They are not bundled '
             'in the source archive or Go executables. This inventory records the native-provider installation '
             'used to prepare these notices; dependencies vary by operating system. Keep each package’s own '
             'notices and source/license obligations if you redistribute it.\n',
             '| Package | Version | Upstream notices |\n| --- | --- | --- |']
    metadata = output(args.python, '-c', '''import importlib.metadata as m,json
print(json.dumps([{"name":d.metadata["Name"],"version":d.version,"files":[str(d.locate_file(f)) for f in (d.files or []) if f.suffix.lower() in ("", ".txt", ".md", ".rst") and f.name.lower().startswith(("license","copying","notice","authors"))]} for d in m.distributions() if d.metadata["Name"].lower() not in ("pip","setuptools","wheel")]))''')
    for package in sorted(json.loads(metadata), key=lambda p: p['name'].lower()):
        copied = []
        if not package['files']:
            fallback = ROOT / 'licenses/upstream' / slug(package['name']) / 'LICENSE.txt'
            if fallback.exists():
                package['files'] = [str(fallback)]
        for index, name in enumerate(package['files']):
            source = Path(name)
            target = ROOT / 'licenses/python' / slug(package['name']) / f'{index}-{source.name}'
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(source, target)
            copied.append(f'[{source.name}]({target.relative_to(ROOT).as_posix()})')
        text.append(f'| `{package["name"]}` | `{package["version"]}` | {", ".join(copied) or "See installed distribution"} |')
    text += ['', '**pyscard:** the supplied license is GNU LGPL version 2.1. It is an optional, '
             'separately installed dependency; Signal Atlas does not relicense it as MIT.\n',
             'Regenerate this inventory after dependency/toolchain upgrades and review the changed '
             'notices. `go.mod`, `go.sum`, `package-lock.json`, and `requirements-native.txt` remain '
             'the authoritative dependency manifests.\n']
    (ROOT / 'THIRD_PARTY_NOTICES.md').write_text('\n'.join(text))
    print('Updated THIRD_PARTY_NOTICES.md and licenses/')


if __name__ == '__main__':
    main()
